package com.github.lamba92.firebasemultiplatform.auth

expect class PlatformSpecificFirebaseAuth
expect interface PlatformSpecificAuthResult
expect abstract class PlatformSpecificFirebaseUser
expect abstract class PlatformSpecificAuthCredential
expect interface PlatformSpecificActionCodeResult
expect class PlatformSpecificGetTokenResults
expect interface PlatformSpecificFirebaseUserMetadata
expect interface PlatformSpecificUserInfo
expect class PlatformSpecificUserProfileChangeRequest
expect class PlatformSpecificUserProfileChangeRequestBuilder
expect class PlatformSpecificPhoneAuthProvider
expect class PlatformSpecificPhoneAuthCredential : PlatformSpecificAuthCredential
expect interface PlatformSpecificAdditionalUserInfo
expect class PlatformSpecificGithubAuthCredential : PlatformSpecificAuthCredential
expect abstract class PlatformSpecificAuthProvider
expect class PlatformSpecificOAuthProvider : PlatformSpecificAuthProvider
expect class PlatformSpecificOAuthProviderBuilder
expect class PlatformSpecificOAuthProviderCredentialsBuilder